# Generated by Django 4.2.5 on 2023-09-13 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senaback', '0002_remove_pruebasenaback_token_pruebasenaback_rol'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_1', models.CharField(max_length=11)),
                ('nombre_2', models.CharField(max_length=11)),
                ('apellido_1', models.CharField(max_length=15)),
                ('apellido_2', models.CharField(max_length=15)),
                ('tipo_documento', models.CharField(max_length=11)),
                ('numero_documento', models.CharField(max_length=12)),
                ('correo_sena', models.EmailField(max_length=254)),
                ('correo_misena', models.EmailField(max_length=254)),
                ('direccion', models.CharField(max_length=20)),
                ('telefono_1', models.CharField(max_length=15)),
                ('telefono_2', models.CharField(max_length=15)),
                ('tipo_contrato', models.CharField(max_length=13)),
                ('fecha_inicio_contrato', models.DateField()),
                ('fecha_fin_contrato', models.DateField()),
                ('firma_digital', models.ImageField(upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='pruebasenaback',
            name='rol',
        ),
    ]
