# Generated by Django 4.2.5 on 2023-09-13 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('senaback', '0005_alter_usuarios_nombre_2'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuarios',
            new_name='Usuario',
        ),
    ]
