# Generated by Django 4.2.4 on 2023-09-29 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('senaback', '0007_elementoconsumible_elementodevolutivo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='elementoconsumible',
            old_name='cantidad_elementos_disponibles',
            new_name='cantidad_total',
        ),
        migrations.RemoveField(
            model_name='elementoconsumible',
            name='cantidad_elementos_total',
        ),
    ]
